[versions]
exposed = "1.0.0-rc-2"
h2 = "2.4.240"
sqlite = "3.50.3.0"

[libraries]
exposed-core = { module = "org.jetbrains.exposed:exposed-core", version.ref = "exposed" }
exposed-dao = { module = "org.jetbrains.exposed:exposed-dao", version.ref = "exposed" }
exposed-jdbc = { module = "org.jetbrains.exposed:exposed-jdbc", version.ref = "exposed" }
h2 = { module = "com.h2database:h2", version.ref = "h2" }
sqlite-jdbc = { module = "org.xerial:sqlite-jdbc", version.ref = "sqlite" }


[bundles]
exposed = [
    "exposed-core",
    "exposed-dao",
    "exposed-jdbc"
]
exposed-h2 = [
    "exposed-core",
    "exposed-dao",
    "exposed-jdbc",
    "h2"
]
exposed-sqlite = [
    "exposed-core",
    "exposed-dao",
    "exposed-jdbc",
    "sqlite-jdbc"
]

[plugins]